//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_DateFight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_DateFight()
        {
            this.db_FightState = new HashSet<db_FightState>();
            this.db_Follow = new HashSet<db_Follow>();
            this.db_QRCode = new HashSet<db_QRCode>();
            this.db_UnAnswer = new HashSet<db_UnAnswer>();
        }
    
        public int DateID { get; set; }
        public Nullable<int> STeamID { get; set; }
        public Nullable<int> ETeamID { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<System.DateTime> FightTime { get; set; }
        public string FightAddress { get; set; }
        public string FightAddress1 { get; set; }
        public string SFightPic { get; set; }
        public string EFightPic { get; set; }
        public string FightIntroduce { get; set; }
        public string FightResult { get; set; }
        public Nullable<int> WinTeamID { get; set; }
        public string CurrentState { get; set; }
        public Nullable<int> UpdateTeamID { get; set; }
        public string LiveLink { get; set; }
        public Nullable<int> HomeShow { get; set; }
        public byte[] Systime { get; set; }
    
        public virtual db_Team db_Team { get; set; }
        public virtual db_Team db_Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_FightState> db_FightState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Follow> db_Follow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_QRCode> db_QRCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_UnAnswer> db_UnAnswer { get; set; }
    }
}
