//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_GuessFightLink
    {
        public int ID { get; set; }
        public Nullable<int> GuessID { get; set; }
        public Nullable<int> FID { get; set; }
        public byte[] System { get; set; }
    
        public virtual db_GuessAndVote db_GuessAndVote { get; set; }
        public virtual db_GuessFight db_GuessFight { get; set; }
    }
}
