//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_GameRecord
    {
        public int GameRecordID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> BoBoID { get; set; }
        public Nullable<System.DateTime> ApplyTIme { get; set; }
        public Nullable<int> IsCancel { get; set; }
        public Nullable<int> State { get; set; }
        public byte[] SysTime { get; set; }
    
        public virtual db_Game db_Game { get; set; }
        public virtual db_Team db_Team { get; set; }
        public virtual db_User db_User { get; set; }
    }
}
