//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_GuessOption
    {
        public int OptionID { get; set; }
        public Nullable<int> GuessID { get; set; }
        public string OptionName { get; set; }
        public string OptionPic { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Odds { get; set; }
        public byte[] SysTime { get; set; }
    
        public virtual db_GuessAndVote db_GuessAndVote { get; set; }
    }
}
