//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_GuessRecord
    {
        public int GuessRecordID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GuessID { get; set; }
        public Nullable<int> OptionID { get; set; }
        public Nullable<int> BetMoney { get; set; }
        public string Result { get; set; }
        public Nullable<int> WinMoney { get; set; }
        public Nullable<int> FinalMoney { get; set; }
        public Nullable<int> GuessType { get; set; }
        public Nullable<System.DateTime> GuessTime { get; set; }
        public Nullable<decimal> Odds { get; set; }
        public byte[] SysTime { get; set; }
    
        public virtual db_User db_User { get; set; }
    }
}
