//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_PlayRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_PlayRecord()
        {
            this.db_PlayRecordPartner = new HashSet<db_PlayRecordPartner>();
            this.db_PlayRecordUser = new HashSet<db_PlayRecordUser>();
            this.db_PlayRecordComment = new HashSet<db_PlayRecordComment>();
        }
    
        public int PlayRecordID { get; set; }
        public string PlayRecordCode { get; set; }
        public string GameName { get; set; }
        public string VSPlace { get; set; }
        public string GameRoom { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string State { get; set; }
        public Nullable<int> Income { get; set; }
        public string Remark { get; set; }
        public byte[] SysTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_PlayRecordPartner> db_PlayRecordPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_PlayRecordUser> db_PlayRecordUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_PlayRecordComment> db_PlayRecordComment { get; set; }
    }
}
