//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_QRCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_QRCode()
        {
            this.db_BarQRCode = new HashSet<db_BarQRCode>();
        }
    
        public int QID { get; set; }
        public int DateID { get; set; }
        public string CodeStr { get; set; }
        public System.DateTime EndDate { get; set; }
        public int State { get; set; }
        public byte[] SysTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_BarQRCode> db_BarQRCode { get; set; }
        public virtual db_DateFight db_DateFight { get; set; }
    }
}
