//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_AssetRecord
    {
        public int GainRecordID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> TrueMoney { get; set; }
        public Nullable<int> VirtualMoney { get; set; }
        public Nullable<System.DateTime> GainTime { get; set; }
        public string State { get; set; }
        public string GainWay { get; set; }
        public string Remark { get; set; }
        public string OutTradeno { get; set; }
        public string TransactionID { get; set; }
        public string TradeType { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public byte[] SysTime { get; set; }
    
        public virtual db_User db_User { get; set; }
    }
}
