//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HiGame_V1Entities : DbContext
    {
        public HiGame_V1Entities()
            : base("name=HiGame_V1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_Article> db_Article { get; set; }
        public virtual DbSet<db_ArticleComment> db_ArticleComment { get; set; }
        public virtual DbSet<db_AssetRecord> db_AssetRecord { get; set; }
        public virtual DbSet<db_BarQRCode> db_BarQRCode { get; set; }
        public virtual DbSet<db_BarUser> db_BarUser { get; set; }
        public virtual DbSet<db_BoBo> db_BoBo { get; set; }
        public virtual DbSet<db_CommonUseHero> db_CommonUseHero { get; set; }
        public virtual DbSet<db_Contribute> db_Contribute { get; set; }
        public virtual DbSet<db_DateFight> db_DateFight { get; set; }
        public virtual DbSet<db_DateFightScore> db_DateFightScore { get; set; }
        public virtual DbSet<db_Episode> db_Episode { get; set; }
        public virtual DbSet<db_EpisodeComment> db_EpisodeComment { get; set; }
        public virtual DbSet<db_FightResult> db_FightResult { get; set; }
        public virtual DbSet<db_FightState> db_FightState { get; set; }
        public virtual DbSet<db_Follow> db_Follow { get; set; }
        public virtual DbSet<db_Game> db_Game { get; set; }
        public virtual DbSet<db_GameBoBo> db_GameBoBo { get; set; }
        public virtual DbSet<db_GameIDofUser> db_GameIDofUser { get; set; }
        public virtual DbSet<db_GameInfoofPlatform> db_GameInfoofPlatform { get; set; }
        public virtual DbSet<db_GameRecord> db_GameRecord { get; set; }
        public virtual DbSet<db_GuessAndVote> db_GuessAndVote { get; set; }
        public virtual DbSet<db_GuessComment> db_GuessComment { get; set; }
        public virtual DbSet<db_GuessFight> db_GuessFight { get; set; }
        public virtual DbSet<db_GuessFightLink> db_GuessFightLink { get; set; }
        public virtual DbSet<db_GuessOption> db_GuessOption { get; set; }
        public virtual DbSet<db_GuessRecord> db_GuessRecord { get; set; }
        public virtual DbSet<db_LiveVideo> db_LiveVideo { get; set; }
        public virtual DbSet<db_MatchGuess> db_MatchGuess { get; set; }
        public virtual DbSet<db_Message> db_Message { get; set; }
        public virtual DbSet<db_MyCollection> db_MyCollection { get; set; }
        public virtual DbSet<db_NetBar> db_NetBar { get; set; }
        public virtual DbSet<db_Partner> db_Partner { get; set; }
        public virtual DbSet<db_PartnerTime> db_PartnerTime { get; set; }
        public virtual DbSet<db_PlayRecord> db_PlayRecord { get; set; }
        public virtual DbSet<db_PlayRecordComment> db_PlayRecordComment { get; set; }
        public virtual DbSet<db_PlayRecordPartner> db_PlayRecordPartner { get; set; }
        public virtual DbSet<db_PlayRecordUser> db_PlayRecordUser { get; set; }
        public virtual DbSet<db_QRCode> db_QRCode { get; set; }
        public virtual DbSet<db_Recruit> db_Recruit { get; set; }
        public virtual DbSet<db_Report> db_Report { get; set; }
        public virtual DbSet<db_SysMessage> db_SysMessage { get; set; }
        public virtual DbSet<db_Team> db_Team { get; set; }
        public virtual DbSet<db_TeamBlog> db_TeamBlog { get; set; }
        public virtual DbSet<db_TeamRemoveUser> db_TeamRemoveUser { get; set; }
        public virtual DbSet<db_TeamUser> db_TeamUser { get; set; }
        public virtual DbSet<db_UnAnswer> db_UnAnswer { get; set; }
        public virtual DbSet<db_User> db_User { get; set; }
        public virtual DbSet<View_TeamUserGamePower> View_TeamUserGamePower { get; set; }
    }
}
